Document: font-basisschrift
Title: Debian font-basisschrift Manual
Author: <insert document author here>
Abstract: This manual describes what font-basisschrift is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/font-basisschrift/font-basisschrift.sgml.gz

Format: postscript
Files: /usr/share/doc/font-basisschrift/font-basisschrift.ps.gz

Format: text
Files: /usr/share/doc/font-basisschrift/font-basisschrift.text.gz

Format: HTML
Index: /usr/share/doc/font-basisschrift/html/index.html
Files: /usr/share/doc/font-basisschrift/html/*.html
